draft: twelve app with sentry, buildinfo and update deps with depdencies injection
morphysm/famed-github-backend pull request #14
Opened 2022-06-15 21:55 UTC by GreyXor

- versionned tag
- user agent for http client
- deps injection with logger and config
- sentry client
- XDG and standards path for config
- new error lib that handle sentry

more's coming

2022-06-20 12:06 UTC, KilianKae commented on internal/devtoolkit/devtoolkit.go
> +	"github.com/morphysm/famed-github-backend/internal/config"
Please sort imports.

2022-06-20 12:10 UTC, KilianKae commented on internal/devtoolkit/devtoolkit.go
> +	// New configuration, based on environment variables and file
`and configuration files` ?

2022-06-20 12:11 UTC, KilianKae commented on internal/devtoolkit/devtoolkit.go
> +		Dsn:              "https://foo@bar.ingest.sentry.io/TEST",
I think this should be passed from the config?

2022-06-20 19:21 UTC, GreyXor commented on internal/devtoolkit/devtoolkit.go
> +		Dsn:              "https://foo@bar.ingest.sentry.io/TEST",
Love the idea! I will make the change when the other PR config is merged

2022-06-20 19:45 UTC, GreyXor commented on main.go
> +	if arguments.Server != nil {
I changed this

2022-06-21 08:32 UTC, KilianKae requested changes

2022-06-21 08:32 UTC, KilianKae commented on main.go
> +	// be sure to flush Sentry
Nitpick: `// Flush Sentry on program end/shutdown (or chose one you find more appropriate)`

2022-06-21 08:32 UTC, KilianKae commented on main.go
> +	if arguments.Server != nil {
Fine by me, I think if more arguments are passed you can probably move the code in the if block to a function.

2022-06-21 12:26 UTC, KilianKae requested changes

2022-06-21 12:41 UTC, GreyXor commented on main.go
> +	}
--version or --help is handle by `arg.MustParse(arguments)` and MustParse will osExit(0);

2022-06-21 12:45 UTC, KilianKae approved these changes

2022-06-21 13:28 UTC, merged