feat: Scanner integrations
morphysm/famed-github-backend pull request #36
Opened 2022-09-02 10:00 UTC by GreyXor

WIP

2022-09-02 11:50 UTC, KilianKae requested changes

2022-09-02 11:50 UTC, KilianKae commented on assets/assets.go
> +//
remove this line.

2022-09-02 11:50 UTC, KilianKae commented on internal/config/default.go
> +	"scanner.enable":        true,
enable -> enabled
enable is a verb, enabled an adjective, that's more suited to bools.

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/docker.go
> +			panic(err)
return error

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/docker.go
> +			panic(err)
panic on the top level. So in server.go.

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/slither.go
> +// TestSSL https://hub.docker.com/r/drwetter/testssl.sh/tags
Wrong comment.

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/slither.go
> +type Report2 struct {
Could rename to SlitherReport.
And I find it easier to read when each struct is arranged like so:

```
type Report struct {
  Results Results
  Something Somthing
}

type Result struct {
...
}

type Something struct {
...
}
```

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/slither.go
> +		panic(err)
return error

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/slither.go
> +		panic(err)
return error

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/slither.go
> +			panic(err)
return error

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/slither.go
> +		panic(err)
return error

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/slither.go
> +	tr := tar.NewReader(fromContainer)
You might be able to directly use the reader by using the decoder:
https://pkg.go.dev/encoding/json#Decoder

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/slither.go
> +		issueRequest := model.IssueRequest{
Pls use `model.NewIssueRequest(title, body, labels, metadata)` with `metadata := model.NewIssueMetadata(installationIssueID, model.InstallationIssueType, "TODO")` and adapt it to your ScannerIssue, so you might need to pull the branch and create a new type :)

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/slither.go
> +		issueRequest := model.IssueRequest{
And not sure if we should use this many labels. Might start polluting the repo's label space.
Not sure how other projects do it.

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/testssl.go
> +package scanner
Same remarks as with the slither file.

2022-09-02 11:50 UTC, KilianKae commented on internal/docker/scanner/testssl.go
> +	fmt.Printf("%+v\n", issues)
remove this or replace with log

2022-09-02 11:50 UTC, KilianKae commented on internal/famed/handler.go
> +	docker, _ := docker.NewManager()
This should be passed as a function parameter and be initialized in server.go.

2022-09-02 11:50 UTC, KilianKae commented on internal/famed/handler.go
> +	docker, _ := docker.NewManager()
This allows for easier testing.

2022-09-02 11:50 UTC, KilianKae commented on internal/famed/handler.go
> +	docker, _ := docker.NewManager()
"dependency injection"

2022-09-02 11:50 UTC, KilianKae commented on internal/famed/scanner_handler.go
> +func (gH *githubHandler) PostTriggerScanner(ctx echo.Context) error {
in the project we use `c echo.Context`
and `ctx := c.Request().Context()`

2022-09-02 11:50 UTC, KilianKae commented on internal/famed/scanner_handler.go
> +	output, _ := gH.docker.Execute(r.Name+":"+r.Version, r.Params)
`output` -> `issues`

2022-09-02 11:50 UTC, KilianKae commented on internal/famed/scanner_handler.go
> +	output, _ := gH.docker.Execute(r.Name+":"+r.Version, r.Params)
makes it clearer what the output is

2022-09-02 11:50 UTC, KilianKae commented on internal/famed/scanner_handler.go
> +	r := new(Request)
the convention here is
```
var request Request
if err := ctx.Bind(request); err != nil {
return echo.NewHTTPError(http.StatusBadGateway)
}
```

2022-09-02 11:50 UTC, KilianKae commented
General Feedback 

- Move choice of scanners to server.go, this is also where you can check config and decide which scanners are active and if they are active at all. Especially useful for testing, when we do not have the scanners running on our machines.
- I know this is not idiomatic but rather longer and explicit names instead of shot and unclear ones (but this is just me)
- Make sure all tests are running:  `go test $(go list ./... | grep -v /providersfakes) -race -coverprofile=coverage.out -covermode=atomic`

2022-09-03 16:50 UTC, GreyXor commented on assets/assets.go
> +//
It's `go fmt` adding this empty comment line.
Exemple here : https://go.dev/play/p/au4x9xPHSrA
you can click on `Format` button and check the behavior of the official fomatter.

Do you really want me to remove it?

2022-09-03 16:59 UTC, GreyXor commented on internal/config/default.go
> +	"scanner.enable":        true,
Finally I'll change this into something better.
No more `scanner.enable` but `scanner.testssl`, `scanner.slither` etc.
and scanner handler will be enabled if any `scanner.*` is `true`.

2022-09-04 13:00 UTC, GreyXor commented on internal/docker/scanner/slither.go
> +	tr := tar.NewReader(fromContainer)
the json decoder here? i'm not sure what you talking about

2022-09-04 15:50 UTC, GreyXor commented on internal/docker/scanner/slither.go
> +		issueRequest := model.IssueRequest{
Done, just not sure about the installationIssueID ?

2022-09-04 20:14 UTC, GreyXor commented
> 
Thank you, i'm just not sure about 2 tests failing

2022-09-05 08:42 UTC, KilianKae commented on assets/assets.go
> +//
Ok strange. Well, it would revert each time. So let's keep it.

2022-09-05 09:03 UTC, KilianKae requested changes

2022-09-05 09:03 UTC, KilianKae commented on internal/famed/blue_team_handler_test.go
> +	"github.com/morphysm/famed-github-backend/internal/docker"
Pls sort imports.

2022-09-05 09:03 UTC, KilianKae commented on internal/docker/scanner/testssl.go
> +
I think you could remove this empty line.

2022-09-05 09:03 UTC, KilianKae commented on internal/famed/comments_update_handler_test.go
> +	"github.com/morphysm/famed-github-backend/internal/docker/scanner"
Sort imports.

2022-09-05 09:03 UTC, KilianKae commented on internal/famed/event_installation_handler_test.go
> +	"github.com/morphysm/famed-github-backend/internal/docker/scanner"
Sort imports.

2022-09-05 09:03 UTC, KilianKae commented on internal/famed/event_installation_repo_handler_test.go
> +	"github.com/morphysm/famed-github-backend/internal/docker"
Sort imports

2022-09-05 09:03 UTC, KilianKae commented on internal/famed/event_issues_handler_test.go
> +	"github.com/morphysm/famed-github-backend/internal/docker/scanner"
Sort imports

2022-09-05 09:05 UTC, KilianKae requested changes

2022-09-05 09:05 UTC, KilianKae commented on internal/famed/handler.go
> +		docker:                   dockerManager,
I think it would make more logical sense to move the dockermanger to after `githubInstallationClient` and before `famedConfig`,

2022-09-05 09:06 UTC, KilianKae requested changes

2022-09-05 09:06 UTC, KilianKae commented on internal/famed/badge_handler_test.go
> +			githubHandler := famed.NewHandler(nil, fakeInstallationClient, famedConfig, "testBaseURL", Now, dockerManager)
Would it be possible to pass nil instead of the `dockerManager`?

2022-09-05 09:19 UTC, GreyXor commented on internal/famed/badge_handler_test.go
> +			githubHandler := famed.NewHandler(nil, fakeInstallationClient, famedConfig, "testBaseURL", Now, dockerManager)
Somewhere we have a dockerManager.Execute() which will then surely fail

2022-09-05 09:31 UTC, KilianKae approved these changes

2022-09-06 09:45 UTC, KilianKae approved these changes

2022-09-06 13:55 UTC, KilianKae requested changes

2022-09-06 13:55 UTC, KilianKae commented on internal/docker/scanner/scanner.go
> +	"mime/multipart"
Duplicate import

2022-09-06 13:55 UTC, KilianKae commented on internal/famed/event_installation_handler_test.go
> +	"github.com/morphysm/famed-github-backend/internal/devtoolkit"
unsorted imports

2022-09-06 13:55 UTC, KilianKae commented on internal/famed/event_installation_repo_handler_test.go
> +	"github.com/morphysm/famed-github-backend/internal/devtoolkit"
unsorted

2022-09-06 13:55 UTC, KilianKae commented on internal/famed/handler.go
unnecessary new line

2022-09-06 14:27 UTC, KilianKae approved these changes

2022-09-07 07:51 UTC, KilianKae approved these changes

2022-09-07 08:42 UTC, merged